### ISSUE TITLE
Virustotal showing detections

### ISSUE THREAD

**Issue by Opencode101** [itschasa/Discord-Backup#24]
tbh idk much but i ran it thru virus total and it came up with 12 trojans on the .exe
![Screenshot 2023-08-24 230333](https://github.com/itschasa/Discord-Backup/assets/112879321/9a965ad8-2ad0-4ae1-bbc1-416253fb2633)

**Comment by itschasa** [comment]
i use pyinstaller to convert the source code to an exe.

unfortunately, because of script kiddies using this wonderful package for hiding malware, anything that is built with this package is automatically seen as malware by some anti viruses.

if you want to, read through the code yourself, build it yourself, or do whatever to convince yourself that this isn't malware.

over 1000 downloads, and yet no one is complaining of being hacked.

**Comment by itschasa** [comment]
Leaving this unlocked to allow discussion and questions to be asked.
